### PR TITLE
Add event detail method to client

### PR DESCRIPTION
**Pull request by fabre-thibaud**

### CODE REVIEW

**Comment by winzou** [comment]
Great, thanks!

**Comment by winzou** [comment]
@fabre-thibaud are you using the lib? I would be happy to have your feedback on it.

**Comment by fabre-thibaud** [comment]
Yes I am. It works fine, out of the box. Other than that missing method, I had no issues using it.

Maybe one detail would be to allow using other HTTP clients (we use Guzzle mainly, and having to add another HTTP client in my dependencies saddens me) instead of BuzzClient

**Comment by winzou** [comment]
You're totally right, I don't even remember why I chose Buzz back then.
If you are able to do a PR to switch to something like `php-http/httplug` (implementation-independant) I would be happy to merge it!

**Pull request merged**
